### ISSUE TITLE
goal-masterの説明

### ISSUE THREAD

**Issue by forno** [CIR-KIT/cirkit_waypoint_manager#15]
`fifth_robot_pkg` にて作成した、なるべくクリーンに作成した `waypoint_navigation` 相当のパッケージ `goal_sender` を引っ張ってきました。

何かの参考にしてくだされば幸いです。 

また、引っ張るときに直接サブディレクトリに移す方法がよくわからなかったので一回ルートに展開してからムーブでディレクトリに移動させています。
引っ張り方に問題があったり、邪魔なんだけど、という場合は適切な取得や削除をおねがいします。

**Comment by AriYu** [comment]
@forno 
これに関しては別リポジトリで育てていきませんか？
というのも、一応これはこれで動いた実績もあるので、もちろんコードが汚いのはあるのですが、残しておけたらと思っています。

**Comment by forno** [comment]
なるほど。それでは完全に別リポジトリで作成しましょうか。

**Comment by AriYu** [comment]
よろしくお願いします。

**Comment by forno** [comment]
ではそのように。こちらのブランチは削除しておきます。
